# spring.application.name=logging-monitoring
# spring.application.name=logging-monitoring

# # H2 in-memory database
# spring.datasource.url=jdbc:h2:mem:loggingdb
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.h2.console.enabled=true
# spring.jpa.hibernate.ddl-auto=create-drop
# spring.jpa.show-sql=false

# # Logging levels
# logging.level.root=INFO
# logging.level.com.assignment.logging=DEBUG
# logging.level.org.springframework.web=WARN

# # Log file output
# logging.file.name=logs/app.log

spring.application.name=logging-monitoring

# MySQL database
spring.datasource.url=jdbc:mysql://localhost:3306/loggingdb?createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Logging levels
logging.level.root=INFO
logging.level.com.assignment.logging=DEBUG
logging.level.org.springframework.web=WARN

# Log file output
logging.file.name=logs/app.log